# Generated by Django 5.2.16 on 2026-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Owner Profile', 'verbose_name_plural': 'Owner Profiles'},
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='business_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRANSPORT_AGENCY', 'Transport Agency'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='phone_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_profiles/'),
        ),
    ]
