# Generated by Django 5.2.16 on 2026-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_ownerprofile_options_ownerprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
