# Generated by Django 5.2.16 on 2026-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_ownerprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='business_type',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRANSPORT_AGENCY', 'Transport Agency')], default='INDIVIDUAL', max_length=30),
        ),
    ]
