# Generated by Django 5.2.16 on 2026-08-10 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_remove_ownerprofile_business_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ownerprofile',
            index=models.Index(fields=['city'], name='owners_owne_city_1456b7_idx'),
        ),
    ]
