# Generated by Django 5.2.16 on 2026-08-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_ownerprofile_owners_owne_city_1456b7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('TEMPO', 'Tempo'), ('TRAILER', 'Trailer'), ('DUMPER', 'Dumper'), ('OTHER', 'Other')], max_length=20)),
                ('number_of_drivers', models.PositiveIntegerField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('experience_required', models.PositiveIntegerField(default=0)),
                ('license_type', models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('TRANSPORT', 'Transport')], max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='owners.ownerprofile')),
            ],
            options={
                'verbose_name': 'Driver Requirement',
                'verbose_name_plural': 'Driver Requirements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city'], name='owners_driv_city_dc1b10_idx'), models.Index(fields=['state'], name='owners_driv_state_2c46c5_idx'), models.Index(fields=['vehicle_type'], name='owners_driv_vehicle_9fc1d9_idx'), models.Index(fields=['status'], name='owners_driv_status_e94797_idx')],
            },
        ),
    ]
