# Generated by Django 5.2.16 on 2026-08-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driverprofile_preferred_vehicle'),
        ('owners', '0006_driverrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='drivers.driverprofile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='owners.driverrequirement')),
            ],
            options={
                'verbose_name': 'Driver Application',
                'verbose_name_plural': 'Driver Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='owners_driv_status_9bfa9e_idx'), models.Index(fields=['driver'], name='owners_driv_driver__816099_idx'), models.Index(fields=['requirement'], name='owners_driv_require_7671b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'requirement'), name='unique_driver_requirement_application')],
            },
        ),
    ]
