# Generated by Django 5.2.16 on 2026-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_driverapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='owner_response',
            field=models.TextField(blank=True),
        ),
    ]
