# Generated by Django 5.2.16 on 2026-07-30 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('license_type', models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('Transport', 'Transport')], max_length=20)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('preferred_vehicle', models.CharField(choices=[('Truck', 'Truck'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Tempo', 'Tempo'), ('Trailer', 'Trailer'), ('Other', 'Other')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('expected_salary', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
