# Generated by Django 5.2.16 on 2026-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Profile', 'verbose_name_plural': 'Driver Profiles'},
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='experience',
            field=models.PositiveIntegerField(help_text='Years of driving experience'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_type',
            field=models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('TRANSPORT', 'Transport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='preferred_vehicle',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('TEMPO', 'Tempo'), ('TRAILER', 'Trailer'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
