# Generated by Django 5.2.16 on 2026-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driverprofile_options_driverprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of driving experience'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_type',
            field=models.CharField(blank=True, choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('TRANSPORT', 'Transport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='preferred_vehicle',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Truck'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('TEMPO', 'Tempo'), ('TRAILER', 'Trailer'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
