# Generated by Django 5.2.16 on 2026-08-10 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['city'], name='drivers_dri_city_763abc_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['available'], name='drivers_dri_availab_f48e66_idx'),
        ),
    ]
