# Generated by Django 5.2.16 on 2026-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driverprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='preferred_vehicle',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Truck'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('TEMPO', 'Tempo'), ('TRAILER', 'Trailer'), ('DUMPER', 'Dumper'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
